# Netlify Configuration for OurJourney

[build]
  # Build command
  command = "npm run build"
  
  # Directory to deploy (Vite output)
  publish = "dist"
  
  # Build environment variables
  # Set these in Netlify dashboard for security
  # VITE_API_URL = "https://your-backend.onrender.com"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache the main HTML file
    Cache-Control = "no-cache, no-store, must-revalidate"

# Environment variables (set in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Deploy contexts for different branches
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

# Functions (if we add Netlify Functions later)
[functions]
  directory = "netlify/functions"