# Netlify Configuration for OurJourney
# This file overrides any UI settings

[build]
  # Base directory where frontend code lives
  base = "frontend"
  
  # Build command - force install all dependencies
  command = "NODE_ENV=development npm ci && npm run build"
  
  # Directory with built files (relative to base)
  publish = "dist"
  
  # Functions directory (relative to base)
  functions = "netlify/functions"

[build.environment]
  # Use Node 20
  NODE_VERSION = "20"
  # Ensure npm installs all dependencies
  NPM_FLAGS = "--include=dev"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"